import multiprocessing as mp
import warnings
from typing import Literal, Sequence

import keras

from bayesflow.approximators import Approximator
from bayesflow.experimental.graphical_approximator.shape_operations import resolve_shapes
from bayesflow.networks import InferenceNetwork, SummaryNetwork
from bayesflow.utils import logging
from bayesflow.utils.serialization import deserialize, serializable, serialize

from ...adapters import Adapter
from ...datasets import OfflineDataset, OnlineDataset
from ...networks.standardization import Standardization
from ..graphical_simulator import GraphicalSimulator, SimulationOutput
from ..graphs import InvertedGraph
from .network_assignment import (
    inference_conditions_by_network,
    inference_variables_by_network,
    summary_inputs_by_network,
)
from .shape_inference import (
    inference_condition_shapes_by_network,
    inference_variable_shapes_by_network,
    summary_input_shapes_by_network,
)


@serializable("bayesflow.experimental")  # type: ignore[missing-argument]
class GraphicalApproximator(Approximator):
    """
    Amortized inference for probabilistic models defined by directed acyclic graphs.

    This approximator implements amortized Bayesian inference for simulation-based
    models whose probabilistic structure can be expressed as a directed acyclic
    graph (DAG). The dependency structure is encoded in an
    :class:`bayesflow.experimental.graphs.InvertedGraph`, which specifies the order
    in which variables are summarized, conditioned on, and inferred.
    """

    def __init__(
        self,
        graph: InvertedGraph,
        *,
        adapter: Adapter | Literal["auto"] = "auto",
        inference_networks: Sequence[InferenceNetwork],
        summary_networks: Sequence[SummaryNetwork] | None = None,
        standardize: str | Sequence[str] | None = "all",
        **kwargs,
    ):
        """
        Parameters
        ----------
        graph : bayesflow.experimental.graphs.InvertedGraph
            InvertedGraph capturing the dependency structure. Usually obtained by calling
            the :py:meth:`invert` method of a :py:class:`SimulationGraph`.
        adapter : bayesflow.adapters.Adapter
            Adapter for data processing. You can use :py:meth:`build_adapter`
            to create it.
        inference_networks : list[InferenceNetwork]
            The inference networks used for posterior estimation.
            Each network is responsible for a subset of variables, as
            determined by the network composition defined by the supplied `graph`.
            Call the :py:meth:`network_composition` method of the `InvertedGraph` for an
            overview of how variables are assigned to inference networks.
        summary_networks : list[SummaryNetwork], optional
            The summary networks used for data summarization (default is None).
        standardize : str | Sequence[str] | None
            The variables to standardize before passing to the networks. Can be either
            "all" or any subset of the variables generated by the SimulationGraph contained
            in the `simulation_graph` field of the supplied InvertedGraph (default is "all").
        **kwargs : dict, optional
            Additional arguments passed to the :py:class:`bayesflow.approximators.Approximator` class.
        """

        super().__init__(**kwargs)
        self.graph = graph
        self.adapter = adapter
        self.inference_networks = inference_networks
        self.summary_networks = summary_networks

        # precompute frequently used quantities
        self.output_shapes = self.graph.simulation_graph.output_shapes()
        self.network_composition = self.graph.network_composition()
        self.network_conditions = self.graph.network_conditions()
        self.variable_names = self.graph.simulation_graph.variable_names()

        if isinstance(standardize, str) and standardize != "all":
            self.standardize = [standardize]
        else:
            self.standardize = standardize or []

        if standardize == "all":
            self.standardize_layers = None
        else:
            self.standardize_layers = {var: Standardization(trainable=False) for var in self.standardize}

        if adapter == "auto":
            self.adapter = GraphicalApproximator.build_adapter()

    @classmethod
    def build_adapter(
        cls,
    ) -> Adapter:
        """Create an :py:class:`~bayesflow.adapters.Adapter` suited for the approximator."""

        adapter = Adapter()
        adapter.to_array()
        adapter.convert_dtype("float64", "float32")

        return adapter

    def build_dataset(
        self,
        *,
        batch_size: int,
        num_batches: int,
        adapter: Adapter | None = None,
        simulator: GraphicalSimulator,
        workers: Literal["auto"] | int = "auto",
        use_multiprocessing: bool = False,
        max_queue_size: int = 32,
        **kwargs,
    ) -> OnlineDataset:
        if workers == "auto":
            workers = mp.cpu_count()
            logging.info(f"Using {workers} data loading workers.")

        workers = workers or 1

        return OnlineDataset(
            simulator=simulator,
            batch_size=batch_size,
            num_batches=num_batches,
            adapter=adapter,
            workers=workers,
            use_multiprocessing=use_multiprocessing,
            max_queue_size=max_queue_size,
            augmentations=lambda x: dict(x),
        )

    @classmethod
    def from_config(cls, config):
        return cls(**deserialize(config))

    def get_config(self):
        base_config = super().get_config()
        config = {
            "graph": self.graph,
            "adapter": self.adapter,
            "inference_networks": self.inference_networks,
            "summary_networks": self.summary_networks,
            "standardize": self.standardize,
        }

        return base_config | serialize(config)

    def build(self, data_shapes: dict | None = None, meta_dict: dict | None = None) -> None:
        if not data_shapes:
            data_shapes = self.output_shapes

        # build summary networks
        input_shapes = summary_input_shapes_by_network(self, data_shapes, meta_dict)

        for i, summary_network in enumerate(self.summary_networks or []):
            if not summary_network.built:
                summary_network.build(input_shapes[i])

        # build inference networks
        variable_shapes = inference_variable_shapes_by_network(self, data_shapes, meta_dict)
        condition_shapes = inference_condition_shapes_by_network(self, data_shapes, meta_dict)

        for i, inference_network in enumerate(self.inference_networks):
            if not inference_network.built:
                inference_network.build(variable_shapes[i], condition_shapes[i])

        # build standardization layers
        output_shapes = resolve_shapes(data_shapes, meta_dict)

        if self.standardize == "all":
            self.standardize = list(output_shapes.keys())
            self.standardize_layers = {var: Standardization(trainable=False) for var in self.standardize}

        for var in self.standardize:
            self.standardize_layers[var].build(output_shapes[var])

        self.built = True

    def compute_metrics(self, stage: str = "training", **kwargs):
        """
        Computes loss and tracks metrics for the inference and summary networks.

        This method orchestrates the end-to-end computation of metrics and loss for a model
        with both inference and optional summary network. It handles standardization of input
        variables, combines summary outputs with inference conditions when necessary, and
        aggregates loss and all tracked metrics into a unified dictionary. The returned dictionary
        includes both the total loss and all individual metrics, with keys indicating their source.

        Parameters
        ----------
        stage : str, optional
            Current training stage (e.g., "training", "validation", "inference"). Controls
            the behavior of standardization and some metric computations (default is "training").

        Returns
        -------
        metrics : dict[str, Tensor]
            Dictionary containing the total loss under the key "loss", as well as all tracked
            metrics for the inference and summary networks. Each metric key is prefixed with
            "inference_" or "summary_" to indicate its source.
        """
        # compute summary metrics
        summary_metrics = {}

        summary_inputs = summary_inputs_by_network(self, kwargs)

        for i, summary_network in enumerate(self.summary_networks or []):
            summary_metrics[i] = summary_network.compute_metrics(summary_inputs[i], stage=stage)
            summary_metrics[i].pop("outputs")

        # compute inference metrics
        inference_variables = inference_variables_by_network(self, kwargs)
        inference_conditions = inference_conditions_by_network(self, kwargs)

        inference_metrics = {}
        for i, inference_network in enumerate(self.inference_networks):
            inference_metrics[i] = inference_network.compute_metrics(
                inference_variables[i], conditions=inference_conditions[i], stage=stage
            )
        # combine metrics
        total_loss = 0
        combined_metrics = {}

        for i, metric_type in enumerate([summary_metrics, inference_metrics]):
            prefix = "summary_metrics" if i == 0 else "inference_metrics"
            for val, metrics in metric_type.items():
                if "loss" in metrics:
                    total_loss += metrics["loss"]
                for k, v in metrics.items():
                    combined_metrics[f"{prefix}_{val}/{k}"] = v

        combined_metrics["loss"] = total_loss

        return combined_metrics

    def fit(self, *args, **kwargs):
        """
        Trains the approximator on the provided dataset or on-demand data generated from the given simulator.
        If `dataset` is not provided, a dataset is built from the `simulator`.
        If the model has not been built, it will be built using a batch from the dataset.

        Parameters
        ----------
        dataset : keras.utils.PyDataset, optional
            A dataset containing simulations for training. If provided, `simulator` must be None.
        simulator : Simulator, optional
            A simulator used to generate a dataset. If provided, `dataset` must be None.
        **kwargs
            Additional keyword arguments passed to `keras.Model.fit()`, including (see also `build_dataset`):

            batch_size : int or None, default='auto'
                Number of samples per gradient update. Do not specify if `dataset` is provided as a
                `keras.utils.PyDataset`, `tf.data.Dataset`, `torch.utils.data.DataLoader`, or a generator function.
            epochs : int, default=1
                Number of epochs to train the model.
            verbose : {"auto", 0, 1, 2}, default="auto"
                Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch.
            callbacks : list of keras.callbacks.Callback, optional
                List of callbacks to apply during training.
            validation_split : float, optional
                Fraction of training data to use for validation (only supported if `dataset` consists of NumPy arrays
                or tensors).
            validation_data : tuple or dataset, optional
                Data for validation, overriding `validation_split`.
            shuffle : bool, default=True
                Whether to shuffle the training data before each epoch (ignored for dataset generators).
            initial_epoch : int, default=0
                Epoch at which to start training (useful for resuming training).
            steps_per_epoch : int or None, optional
                Number of steps (batches) before declaring an epoch finished.
            validation_steps : int or None, optional
                Number of validation steps per validation epoch.
            validation_batch_size : int or None, optional
                Number of samples per validation batch (defaults to `batch_size`).
            validation_freq : int, default=1
                Specifies how many training epochs to run before performing validation.

        Returns
        -------
        keras.callbacks.History
            A history object containing the training loss and metrics values.

        Raises
        ------
        ValueError
            If both `dataset` and `simulator` are provided or neither is provided.
        """
        if "dataset" in kwargs:
            dataset = OfflineDataset(
                kwargs.pop("dataset"),
                batch_size=kwargs.get("batch_size"),  # type: ignore[invalid-argument-type]
                num_samples=kwargs.get("num_samples"),  # type: ignore[invalid-argument-type]
                adapter=self.adapter,
                augmentations=self.subset_data,
            )

            def generator():
                for i in range(dataset.num_batches or 0):
                    yield dataset[i]

        if "simulator" in kwargs:
            dataset = self.build_dataset(
                simulator=kwargs.pop("simulator"),
                adapter=kwargs.get("adapter"),
                batch_size=kwargs["batch_size"],
                num_batches=kwargs["num_batches"],
            )
            def generator():
                i = 0
                while True:
                    yield dataset[i]
                    i += 1

        if keras.backend.backend() == "tensorflow":
            import tensorflow as tf

            data_shapes = self._data_shapes(dataset[0])
            signature = {
                k: tf.TensorSpec(shape=[None] * (len(v) - 1) + [v[-1]], dtype=tf.float32)
                for k, v in data_shapes.items()
            }
            kwargs.setdefault("steps_per_epoch", dataset.num_batches)
            kwargs["dataset"] = tf.data.Dataset.from_generator(generator, output_signature=signature)
        else:
            kwargs["dataset"] = dataset

        return super().fit(*args, **kwargs, adapter=self.adapter)

    def subset_data(self, data, meta_fn=None):
        output_shapes = self.graph.simulation_graph.output_shapes()

        if not meta_fn:
            meta_fn = self.graph.simulation_graph.meta_fn
            if meta_fn:
                output_shapes = self.graph.simulation_graph.output_shapes(meta_fn())

        output = {}

        for k, v in data.items():
            if k not in output_shapes:
                raise KeyError(f"Unexpected data entry: {k}")

            begin = (0,) * len(keras.ops.shape(v))

            output_shape = list(output_shapes[k])
            output_shape[0] = keras.ops.shape(v)[0]  # replace batch size placeholder
            output_shape = tuple(output_shape)

            # current keras version throws a deprecation warning when using keras.ops.slice even if
            # called approriately
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="Using a non-tuple sequence")
                output[k] = keras.ops.convert_to_numpy(keras.ops.slice(v, begin, output_shape))

        return output

    def _batch_size_from_data(self, data):
        """
        Fetches the current batch size from an input dictionary.
        """
        for key, value in data.items():
            if hasattr(value, "shape"):
                return keras.ops.shape(value)[0]

    def _data_shapes(self, adapted_data: SimulationOutput | dict) -> dict[str, tuple[int]]:
        def _shape_tuple(x) -> tuple[int, ...]:
            shape = keras.ops.shape(x)
            return tuple(int(i) for i in keras.ops.convert_to_numpy(shape))

        return keras.tree.map_structure(_shape_tuple, dict(adapted_data))
