from typing import Literal, Sequence

import keras

from bayesflow.approximators import Approximator
from bayesflow.experimental.graphical_approximator.shape_operations import resolve_shapes
from bayesflow.networks import InferenceNetwork, SummaryNetwork
from bayesflow.utils.serialization import deserialize, serializable, serialize

from ...adapters import Adapter
from ...networks.standardization import Standardization
from ..graphical_simulator import SimulationOutput
from ..graphs import InvertedGraph
from .network_assignment import (
    inference_conditions_by_network,
    inference_variables_by_network,
    summary_inputs_by_network,
)
from .shape_inference import (
    inference_condition_shapes_by_network,
    inference_variable_shapes_by_network,
    summary_input_shapes_by_network,
)


@serializable("bayesflow.experimental")  # type: ignore[missing-argument]
class GraphicalApproximator(Approximator):
    """
    Amortized inference for probabilistic models defined by directed acyclic graphs.

    This approximator implements amortized Bayesian inference for simulation-based
    models whose probabilistic structure can be expressed as a directed acyclic
    graph (DAG). The dependency structure is encoded in an
    :class:`bayesflow.experimental.graphs.InvertedGraph`, which specifies the order
    in which variables are summarized, conditioned on, and inferred.
    """

    def __init__(
        self,
        graph: InvertedGraph,
        *,
        adapter: Adapter | Literal["auto"] = "auto",
        inference_networks: Sequence[InferenceNetwork],
        summary_networks: Sequence[SummaryNetwork] | None = None,
        standardize: str | Sequence[str] | None = "all",
        **kwargs,
    ):
        """
        Parameters
        ----------
        graph : bayesflow.experimental.graphs.InvertedGraph
            InvertedGraph capturing the dependency structure. Usually obtained by calling
            the :py:meth:`invert` method of a :py:class:`SimulationGraph`.
        adapter : bayesflow.adapters.Adapter
            Adapter for data processing. You can use :py:meth:`build_adapter`
            to create it.
        inference_networks : list[InferenceNetwork]
            The inference networks used for posterior estimation.
            Each network is responsible for a subset of variables, as
            determined by the network composition defined by the supplied `graph`.
            Call the :py:meth:`network_composition` method of the `InvertedGraph` for an
            overview of how variables are assigned to inference networks.
        summary_networks : list[SummaryNetwork], optional
            The summary networks used for data summarization (default is None).
        standardize : str | Sequence[str] | None
            The variables to standardize before passing to the networks. Can be either
            "all" or any subset of the variables generated by the SimulationGraph contained
            in the `simulation_graph` field of the supplied InvertedGraph (default is "all").
        **kwargs : dict, optional
            Additional arguments passed to the :py:class:`bayesflow.approximators.Approximator` class.
        """

        super().__init__(**kwargs)
        self.graph = graph
        self.adapter = adapter
        self.inference_networks = inference_networks
        self.summary_networks = summary_networks

        # precompute frequently used quantities
        self.output_shapes = self.graph.simulation_graph.output_shapes()
        self.network_composition = self.graph.network_composition()
        self.network_conditions = self.graph.network_conditions()
        self.variable_names = self.graph.simulation_graph.variable_names()

        if isinstance(standardize, str) and standardize != "all":
            self.standardize = [standardize]
        else:
            self.standardize = standardize or []

        if standardize == "all":
            self.standardize_layers = None
        else:
            self.standardize_layers = {var: Standardization(trainable=False) for var in self.standardize}

        if adapter == "auto":
            self.adapter = GraphicalApproximator.build_adapter()

    @classmethod
    def build_adapter(
        cls,
    ) -> Adapter:
        """Create an :py:class:`~bayesflow.adapters.Adapter` suited for the approximator."""

        adapter = Adapter()
        adapter.to_array()
        adapter.convert_dtype("float64", "float32")

        return adapter

    @classmethod
    def from_config(cls, config):
        return cls(**deserialize(config))

    def get_config(self):
        base_config = super().get_config()
        config = {
            "graph": self.graph,
            "adapter": self.adapter,
            "inference_networks": self.inference_networks,
            "summary_networks": self.summary_networks,
            "standardize": self.standardize,
        }

        return base_config | serialize(config)

    def build(self, data_shapes: dict | None = None, meta_dict: dict | None = None) -> None:
        if not data_shapes:
            data_shapes = self.output_shapes

        # build summary networks
        input_shapes = summary_input_shapes_by_network(self, data_shapes, meta_dict)

        for i, summary_network in enumerate(self.summary_networks or []):
            if not summary_network.built:
                summary_network.build(input_shapes[i])

        # build inference networks
        variable_shapes = inference_variable_shapes_by_network(self, data_shapes, meta_dict)
        condition_shapes = inference_condition_shapes_by_network(self, data_shapes, meta_dict)

        for i, inference_network in enumerate(self.inference_networks):
            if not inference_network.built:
                inference_network.build(variable_shapes[i], condition_shapes[i])

        # build standardization layers
        output_shapes = resolve_shapes(data_shapes, meta_dict)

        if self.standardize == "all":
            self.standardize = list(output_shapes.keys())
            self.standardize_layers = {var: Standardization(trainable=False) for var in self.standardize}

        for var in self.standardize:
            self.standardize_layers[var].build(output_shapes[var])

        self.built = True

    def compute_metrics(self, adapted_data: dict, stage: str = "training"):
        """
        Computes loss and tracks metrics for the inference and summary networks.

        This method orchestrates the end-to-end computation of metrics and loss for a model
        with both inference and optional summary network. It handles standardization of input
        variables, combines summary outputs with inference conditions when necessary, and
        aggregates loss and all tracked metrics into a unified dictionary. The returned dictionary
        includes both the total loss and all individual metrics, with keys indicating their source.

        Parameters
        ----------
        stage : str, optional
            Current training stage (e.g., "training", "validation", "inference"). Controls
            the behavior of standardization and some metric computations (default is "training").

        Returns
        -------
        metrics : dict[str, Tensor]
            Dictionary containing the total loss under the key "loss", as well as all tracked
            metrics for the inference and summary networks. Each metric key is prefixed with
            "inference_" or "summary_" to indicate its source.
        """
        # compute summary metrics
        summary_metrics = {}

        summary_inputs = summary_inputs_by_network(self, adapted_data)

        for i, summary_network in enumerate(self.summary_networks or []):
            summary_metrics[i] = summary_network.compute_metrics(summary_inputs[i], stage=stage)
            summary_metrics[i].pop("outputs")

        # compute inference metrics
        inference_variables = inference_variables_by_network(self, adapted_data)
        inference_conditions = inference_conditions_by_network(self, adapted_data)

        inference_metrics = {}
        for i, inference_network in enumerate(self.inference_networks):
            inference_metrics[i] = inference_network.compute_metrics(
                inference_variables[i], conditions=inference_conditions[i], stage=stage
            )
        # combine metrics
        total_loss = 0
        combined_metrics = {}

        for i, metric_type in enumerate([summary_metrics, inference_metrics]):
            prefix = "summary_metrics" if i == 0 else "inference_metrics"
            for val, metrics in metric_type.items():
                if "loss" in metrics:
                    total_loss += metrics["loss"]
                for k, v in metrics.items():
                    combined_metrics[f"{prefix}_{val}/{k}"] = v

        combined_metrics["loss"] = total_loss

        return combined_metrics

    def _data_shapes(self, adapted_data: SimulationOutput | dict) -> dict[str, tuple[int]]:
        def _shape_tuple(x) -> tuple[int, ...]:
            shape = keras.ops.shape(x)
            return tuple(int(i) for i in keras.ops.convert_to_numpy(shape))

        return keras.tree.map_structure(_shape_tuple, dict(adapted_data))
