dependencies:
  - jupyter
  - jupyterlab
  - keras ~= 3.3.0
  - numpy
  - matplotlib
  - pytest
  - pytest-cov
  - pytest-xdist
  - python >= 3.10, < 3.12
  - seaborn
  - scikit-learn
  - scipy
  - tqdm
  - tox ~= 4.15