name: Publish to PyPI and Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Whether to perform a dry, which skips tagging and publishing."
        required: true
        type: boolean
        default: true
      release_type:
        description: "The type of release. Performs an automatic version bump."
        required: true
        type: choice
        # We explicitly only support minor and patch releases with this workflow.
        # Other release types should be handled manually.
        options: [minor, patch]
        default: patch
      github_release:
        description: "Whether to create a release on GitHub."
        required: true
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # Use environment variables to avoid security vulnerabilities from input injection.
      DRY_RUN: ${{ github.event.inputs.dry_run }}
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}

    # PyPI trusted publishing permissions
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
        fetch-depth: 0  # shallow clone

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Update version string
      run: uv version --bump "RELEASE_TYPE"

    - name: Build wheel
      run: uv build

    - name: Check wheel contents
      run: uvx check-wheel-contents dist/*.whl

    - name: Commit and Tag Version
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pyproject.toml
        if [[ $DRY_RUN == true ]]; then
          echo "Performing a dry run. No commit or tag will be created."
          git commit -m "🚀 Release $VERSION" --dry-run
          git tag v$VERSION
          git push origin --tags --dry-run
        else
          echo "Committing and tagging version $VERSION."
          git commit -m "🚀 Release $VERSION"
          git tag v$VERSION
          git push origin --tags
        fi

    - name: Publish package to PyPI
      run: |
        if [[ $DRY_RUN == true ]]; then
          echo "Performing a dry run. No package will be published."
          uv publish --dry-run
        else
          echo "Publishing package to PyPI."
          uv publish
        fi
