name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Whether to perform a dry run (publish to TestPyPI)"
        required: true
        type: boolean
        default: true
      release_type:
        description: "The type of release. Performs an automatic version bump."
        required: true
        type: choice
        # We explicitly only support minor and patch releases with this workflow.
        # Other release types should be handled manually.
        options: [minor, patch]
        default: patch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # Using the release type only as an environment variable avoids security vulnerabilities from input injection.
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}

    # PyPI trusted publishing permissions
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        fetch-depth: 0  # shallow clone

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Set up Python
      run: uv python install

    - name: Update version string
      run: uv version --bump "RELEASE_TYPE"

    - name: Build wheel
      run: uv build

    - name: Check wheel contents
      run: uvx check-wheel-contents dist/*.whl

    - name: Publish package to TestPyPI
      if: ${{ github.event.inputs.dry_run == true }}
      run: uv publish --publish-url = "https://test.pypi.org/legacy/"

    - name: Publish package to PyPI
      if: ${{ github.event.inputs.dry_run == false }}
      run: uv publish

    - name: Commit and Tag Version
      if: ${{ github.event.inputs.dry_run == false }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pyproject.toml
        git commit -m "🚀 Release $VERSION"
        git tag v$VERSION
        git push origin main --tags
