name: Check Code Style

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - update-workflows
  push:
    branches:
      - main
      - dev
      - update-workflows

jobs:
  set-up-environment:
    name: Set Up Environment

    runs-on: ubuntu-latest

    environment: code-style

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install ruff

  lint:
    name: Run Linter

    needs: set-up-environment

    runs-on: ubuntu-latest

    environment: code-style

    steps:
      - name: Check Linter
        run: ruff check --config pyproject.toml --verbose

  format:
    name: Run Formatter

    needs: set-up-environment

    runs-on: ubuntu-latest

    environment: code-style

    steps:
      - name: Check Formatter
        run: ruff format --config pyproject.toml --check --verbose
