name: Check Code Style

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - update-workflows
  push:
    branches:
      - main
      - dev
      - update-workflows

jobs:
  check-code-style:
    name: Check Code Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: |
          pip install -U pip setuptools wheel
          pip install ruff

      - name: Run Linter
        run: ruff check --config pyproject.toml --verbose

      - name: Run Formatter
        run: ruff format --config pyproject.toml --check --verbose
